#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====

export PANGEO_ENV="pangeo-notebook"

# Load default demo data:
cd /home/jovyan
mkdir data
cd data
wget https://api.ifremer.fr/virtualfleet/data/GLOBAL-ANALYSIS-FORECAST-PHY-001-024/20190101_global-analysis-forecast-phy-001-024.nc
cd /home/jovyan

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
